name: "push"

on:
  push:
    branches:
      - "main"

jobs:
  check:
    runs-on: "ubuntu-latest"
    if: "github.ref == 'refs/heads/main'"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "c032/gha-node@main"
        with:
          build: false

  docker-image:
    runs-on: "ubuntu-latest"
    needs:
      - "check"
    permissions:
      contents: "read"
      packages: "write"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "c032/gha-docker@main"
        with:
          image-name: "${{ github.repository }}"
          registry-username: "${{ github.actor }}"
          registry-password: "${{ secrets.GITHUB_TOKEN }}"
          dockerfile: "./docker/api-production.dockerfile"
